# Generated by Django 3.2.6 on 2021-08-06 11:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('add_date', models.DateField()),
                ('col_name1', models.CharField(blank=True, default='None', max_length=30)),
                ('col_name2', models.CharField(blank=True, default='None', max_length=30)),
                ('col_name3', models.CharField(blank=True, default='None', max_length=30)),
                ('col_name4', models.CharField(blank=True, default='None', max_length=30)),
                ('col_name5', models.CharField(blank=True, default='None', max_length=30)),
                ('col_name6', models.CharField(blank=True, default='None', max_length=30)),
                ('type1', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('type2', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('type3', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('type4', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('type5', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('type6', models.CharField(choices=[('Select...', 'Select...'), ('Full Name', 'Full Name'), ('Email', 'Email'), ('Phone Number', 'Phone Number'), ('Job', 'Job'), ('Company', 'Company'), ('Address', 'Address')], max_length=30)),
                ('order1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
