# Generated by Django 3.2.6 on 2021-08-09 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('type1', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('type2', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('type3', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('type4', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('type5', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('type6', models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30)),
                ('col_name1', models.CharField(blank=True, max_length=30)),
                ('col_name2', models.CharField(blank=True, max_length=30)),
                ('col_name3', models.CharField(blank=True, max_length=30)),
                ('col_name4', models.CharField(blank=True, max_length=30)),
                ('col_name5', models.CharField(blank=True, max_length=30)),
                ('col_name6', models.CharField(blank=True, max_length=30)),
                ('order1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order3', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order4', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order5', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order6', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('rows', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
