# Generated by Django 3.2.6 on 2021-08-14 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('column_seperator', models.CharField(choices=[('1', 'Dot comma (;)'), ('2', 'Comma (,)')], default='Dot Comma(;)', max_length=30)),
                ('string_character', models.CharField(choices=[('1', 'Double quote ()'), ('2', "quote ('')")], default='Double quote()', max_length=30)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30)),
                ('type2', models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30)),
                ('col_name', models.CharField(max_length=30)),
                ('col_name2', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('order2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
