# Generated by Django 3.2.6 on 2021-08-06 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name1',
            new_name='n1',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name2',
            new_name='n2',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name3',
            new_name='n3',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name4',
            new_name='n4',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name5',
            new_name='n5',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='col_name6',
            new_name='n6',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order1',
            new_name='o1',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order2',
            new_name='o2',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order3',
            new_name='o3',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order4',
            new_name='o4',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order5',
            new_name='o5',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='order6',
            new_name='o6',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type3',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type4',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type5',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='type6',
        ),
        migrations.AddField(
            model_name='scheme',
            name='c1',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c2',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c3',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c4',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c5',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c6',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c7',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c8',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='c9',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Choose...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='n7',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='n8',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='n9',
            field=models.CharField(blank=True, default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='o7',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='scheme',
            name='o8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='scheme',
            name='o9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
