# Generated by Django 3.2.6 on 2021-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type1',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type2',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type3',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type4',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type5',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type6',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], default='Select...', max_length=30),
        ),
    ]
