# Generated by Django 3.2.6 on 2021-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='col_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
