# Generated by Django 3.2.6 on 2021-08-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_scheme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='rows',
        ),
    ]
