# Generated by Django 3.2.6 on 2021-08-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210806_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='oorder1',
            new_name='order1',
        ),
    ]
