# Generated by Django 3.2.6 on 2021-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210814_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type2',
            field=models.CharField(blank=True, choices=[('1', 'Select...'), ('2', 'string'), ('3', 'int'), ('4', 'bool'), ('5', 'list'), ('6', 'float'), ('7', 'tuple')], max_length=30),
        ),
    ]
