# Generated by Django 3.2.6 on 2021-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_scheme_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='column_seperator',
            field=models.CharField(choices=[('1', 'Dot comma (;)'), ('2', 'Comma (,)')], default='Dot Comma(;)', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='string_character',
            field=models.CharField(choices=[('1', 'Double quote ("")'), ('2', 'quote ()')], default='Double quote()', max_length=30),
        ),
    ]
