# Generated by Django 3.2.6 on 2021-08-06 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_oorder1_scheme_order1'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
