# Generated by Django 3.2.6 on 2021-08-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheme_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type1',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type2',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type3',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type4',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type5',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type6',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
    ]
