# Generated by Django 3.2.6 on 2021-08-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210806_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='n1',
            new_name='col_name1',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='n2',
            new_name='col_name2',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='n3',
            new_name='col_name3',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='n4',
            new_name='col_name4',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='n5',
            new_name='col_name5',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='n6',
            new_name='col_name6',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o1',
            new_name='order1',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o2',
            new_name='order2',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o3',
            new_name='order3',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o4',
            new_name='order4',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o5',
            new_name='order5',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='o6',
            new_name='order6',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c5',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c6',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c7',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c8',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='c9',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='n7',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='n8',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='n9',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='o7',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='o8',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='o9',
        ),
        migrations.AddField(
            model_name='scheme',
            name='type1',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='type2',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='type3',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='type4',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='type5',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
        migrations.AddField(
            model_name='scheme',
            name='type6',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'Full Name'), ('3', 'Email'), ('4', 'Phone Number'), ('5', 'Job'), ('6', 'Company'), ('7', 'Address')], default='Select...', max_length=30),
        ),
    ]
