# Generated by Django 3.2.6 on 2021-08-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210807_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='type1',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type2',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type3',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type4',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type5',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='type6',
            field=models.CharField(choices=[('1', 'Select...'), ('2', 'name'), ('3', 'email'), ('4', 'phone'), ('5', 'job'), ('6', 'company'), ('7', 'address')], default='Select...', max_length=30),
        ),
    ]
