# Generated by Django 3.2.6 on 2021-08-07 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210807_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
