# Generated by Django 3.2.6 on 2021-08-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_scheme_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='add_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
