# Generated by Django 3.2.6 on 2021-08-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_scheme_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='col_name1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='col_name6',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
