# Generated by Django 3.2.6 on 2021-08-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_scheme_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
